apiVersion: v1
kind: ConfigMap
metadata: 
  name: photostudio-config
data:
  MONGODB_AUTH_URI=mongodb:mongo:27017/artgallery
  MONGODB_FEEDBACK_URI=mongodb:mongo:27017/artgallery
  MONGODB_URI=mongodb:mongo:27017
